import { ArrowDown, ArrowUp, Plus, Save, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "../../lib/supabase-browser";
import type { JourneyItem } from "../JourneyTimeline";

const fallback: JourneyItem[] = [
  { id: "now", eyebrow_fr: "Aujourd’hui", eyebrow_en: "Now", title_fr: "Certificat de spécialisation · Desserts de restaurant", title_en: "Specialist certificate · Restaurant desserts", body_fr: "J’approfondis le dressage, les textures, les sauces et le travail du dessert à l’assiette au Campus 120.", body_en: "At Campus 120, I am developing my plating, textures, sauces and the craft of à la carte desserts." },
  { id: "experience", eyebrow_fr: "Expérience", eyebrow_en: "Experience", title_fr: "Environnement professionnel", title_en: "Professional settings", body_fr: "Je présente chaque création dans son contexte : formation, expérience en entreprise ou travail personnel.", body_en: "I present each creation in its context: education, professional experience or personal work." },
  { id: "outlook", eyebrow_fr: "Horizon", eyebrow_en: "Outlook", title_fr: "Voyager pour apprendre", title_en: "Travel to learn", body_fr: "Je souhaite enrichir ma pratique grâce à des expériences internationales, avec un intérêt particulier pour l’Asie et la Thaïlande.", body_en: "I want to enrich my practice through international experience, with a particular interest in Asia and Thailand." },
];

export default function JourneyEditor({ settings }: { settings: Record<string, unknown> }) {
  const client = useMemo(() => getSupabaseBrowserClient(), []);
  const [items, setItems] = useState<JourneyItem[]>(Array.isArray(settings.items) ? settings.items as JourneyItem[] : fallback);
  const [message, setMessage] = useState("");
  const input = "mt-1 min-h-11 w-full rounded-xl border border-stone-300 bg-white px-3 font-normal outline-none focus:border-amber-700";
  function change(id: string, key: keyof JourneyItem, value: string) { setItems((current) => current.map((item) => item.id === id ? { ...item, [key]: value } : item)); }
  function move(index: number, direction: -1 | 1) { setItems((current) => { const next = [...current]; const target = index + direction; if (target < 0 || target >= next.length) return current; [next[index], next[target]] = [next[target], next[index]]; return next; }); }
  async function save() { if (!client) return; const { error } = await client.from("site_sections").update({ settings: { ...settings, items } }).eq("id", "journey"); setMessage(error ? "Le parcours n’a pas pu être enregistré." : "Le parcours est enregistré."); }
  return <section className="mt-6 rounded-[2rem] border border-stone-200 bg-[#fffdf9] p-4 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-amber-800">Parcours</p><h2 className="mt-1 font-serif text-3xl">Mes étapes</h2><p className="mt-2 text-sm text-stone-600">Je modifie, ajoute, supprime ou réorganise les étapes de la page Parcours.</p><div className="mt-5 grid gap-4">{items.map((item, index) => <article key={item.id} className="rounded-2xl border border-stone-200 bg-white p-4"><div className="mb-3 flex justify-end gap-1"><button type="button" className="grid size-9 place-items-center rounded-lg hover:bg-stone-100" onClick={() => move(index, -1)}><ArrowUp className="size-4" /></button><button type="button" className="grid size-9 place-items-center rounded-lg hover:bg-stone-100" onClick={() => move(index, 1)}><ArrowDown className="size-4" /></button><button type="button" className="grid size-9 place-items-center rounded-lg text-red-700 hover:bg-red-50" onClick={() => setItems((current) => current.filter((entry) => entry.id !== item.id))}><Trash2 className="size-4" /></button></div><div className="grid gap-3 sm:grid-cols-2">{([['eyebrow_fr','Repère FR'],['eyebrow_en','Repère EN'],['title_fr','Titre FR'],['title_en','Titre EN']] as const).map(([key,label]) => <label key={key} className="text-sm font-bold">{label}<input className={input} value={item[key]} onChange={(e) => change(item.id, key, e.target.value)} /></label>)}<label className="text-sm font-bold">Texte FR<textarea className={`${input} min-h-20 py-2`} value={item.body_fr} onChange={(e) => change(item.id, "body_fr", e.target.value)} /></label><label className="text-sm font-bold">Texte EN<textarea className={`${input} min-h-20 py-2`} value={item.body_en} onChange={(e) => change(item.id, "body_en", e.target.value)} /></label></div></article>)}</div><button type="button" className="button-secondary mt-4 w-full gap-2" onClick={() => setItems((current) => [...current, { id: crypto.randomUUID(), eyebrow_fr: "Nouvelle étape", eyebrow_en: "New step", title_fr: "", title_en: "", body_fr: "", body_en: "" }])}><Plus className="size-4" />Ajouter une étape</button>{message && <p className="mt-3 text-sm text-stone-600">{message}</p>}<button type="button" className="button-primary mt-4 w-full gap-2" onClick={() => void save()}><Save className="size-4" />Enregistrer le parcours</button></section>;
}
